
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MOD_ASSIGN = 15;
  public static final int ELSE = 3;
  public static final int IDENT = 9;
  public static final int PLUS = 25;
  public static final int NE_OP = 19;
  public static final int SEMI = 31;
  public static final int WHILE = 4;
  public static final int NOT = 22;
  public static final int AND_OP = 20;
  public static final int GREATER = 30;
  public static final int INTCONST = 10;
  public static final int IF = 2;
  public static final int EQ_OP = 18;
  public static final int SCROPPO_ASSIGN = 14;
  public static final int EOF = 0;
  public static final int DIVIDE = 27;
  public static final int MINUS = 24;
  public static final int OR_OP = 21;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int PARAR = 8;
  public static final int CURLYR = 6;
  public static final int GE_OP = 17;
  public static final int ADD_ASSIGN = 11;
  public static final int MUL = 26;
  public static final int PARAL = 7;
  public static final int SUB_ASSIGN = 12;
  public static final int LE_OP = 16;
  public static final int MODULUS = 28;
  public static final int CURLYL = 5;
  public static final int MUL_ASSIGN = 13;
  public static final int LESS = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "CURLYL",
  "CURLYR",
  "PARAL",
  "PARAR",
  "IDENT",
  "INTCONST",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "MUL_ASSIGN",
  "SCROPPO_ASSIGN",
  "MOD_ASSIGN",
  "LE_OP",
  "GE_OP",
  "EQ_OP",
  "NE_OP",
  "AND_OP",
  "OR_OP",
  "NOT",
  "ASSIGN",
  "MINUS",
  "PLUS",
  "MUL",
  "DIVIDE",
  "MODULUS",
  "LESS",
  "GREATER",
  "SEMI"
  };
}

